# Generated by Django 2.2.16 on 2021-02-14 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Requried, PrimaryKey none-editable', primary_key=True, serialize=False, verbose_name='UUID Identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('title', models.CharField(help_text='Required.', max_length=255, verbose_name='Name')),
                ('description', models.CharField(help_text='Required, Maximum of 255 Characters.', max_length=255, verbose_name='Description')),
                ('min_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Minimum Salary')),
                ('max_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Maximum Salary')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_job_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_job_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
